### ISSUE TITLE
Issue installing pdftk

### ISSUE THREAD

**Issue by AbeHandler** [spl/homebrew-pdftk#11]
Hi. I run `$brew install pdftk` and get the following error

```
Last 15 lines from /Users/ahandler/Library/Logs/Homebrew/pdftk/01.make:
report.cc:33:10: fatal error: gcj/cni.h: No such file or directory
 #include <gcj/cni.h>
          ^~~~~~~~~~~
compilation terminated.
compilation terminated.
attachments.cc:33:10: fatal error: gcj/cni.h: No such file or directory
 #include <gcj/cni.h>
          ^~~~~~~~~~~
compilation terminated.
compilation terminated.
make: *** [passwords.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [report.o] Error 1
make: *** [attachments.o] Error 1
make: *** [pdftk.o] Error 1

```

Any suggestions on how to fix? Thanks.

**Comment by spl** [comment]
@AbeHandler This tap is not expected to work for Mac OS X 10.11 (El Capitan) and above, and therefore not maintained. See the `README.md` for the note. I recommend trying one of the other options described [here](http://stackoverflow.com/questions/32505951/pdftk-server-on-os-x-10-11).
